apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: benchmark-3w
  region: us-east-1
  version: "1.33"

iam:
  withOIDC: true   # necessário para IRSA (acesso S3 sem credentials hardcoded)

managedNodeGroups:
  - name: benchmark-nodes
    instanceType: c6g.xlarge   # 4 vCPU, 16GB RAM
    minSize: 3
    maxSize: 3
    desiredCapacity: 3
    volumeSize: 40
    labels:
      role: benchmark
    tags:
      project: benchmark-3w
